package org.apache.poi.xslf.usermodel;


public enum SlideLayout {

   TITLE("TITLE", 0),
   TEXT("TEXT", 1),
   TWO_COL_TX("TWO_COL_TX", 2),
   TBL("TBL", 3),
   TEXT_AND_CHART("TEXT_AND_CHART", 4),
   CHART_AND_TEXT("CHART_AND_TEXT", 5),
   DGM("DGM", 6),
   CHART("CHART", 7),
   TX_AND_CLIP_ART("TX_AND_CLIP_ART", 8),
   CLIP_ART_AND_TEXT("CLIP_ART_AND_TEXT", 9),
   TITLE_ONLY("TITLE_ONLY", 10),
   BLANK("BLANK", 11),
   TX_AND_OBJ("TX_AND_OBJ", 12),
   OBJ_AND_TX("OBJ_AND_TX", 13),
   OBJ_ONLY("OBJ_ONLY", 14),
   TITLE_AND_CONTENT("TITLE_AND_CONTENT", 15),
   TX_AND_MEDIA("TX_AND_MEDIA", 16),
   MEDIA_AND_TX("MEDIA_AND_TX", 17),
   OBJ_OVER_TX("OBJ_OVER_TX", 18),
   TX_OVER_OBJ("TX_OVER_OBJ", 19),
   TX_AND_TWO_OBJ("TX_AND_TWO_OBJ", 20),
   TWO_OBJ_AND_TX("TWO_OBJ_AND_TX", 21),
   TWO_OBJ_OVER_TX("TWO_OBJ_OVER_TX", 22),
   FOUR_OBJ("FOUR_OBJ", 23),
   VERT_TX("VERT_TX", 24),
   CLIP_ART_AND_VERT_TX("CLIP_ART_AND_VERT_TX", 25),
   VERT_TITLE_AND_TX("VERT_TITLE_AND_TX", 26),
   VERT_TITLE_AND_TX_OVER_CHART("VERT_TITLE_AND_TX_OVER_CHART", 27),
   TWO_OBJ("TWO_OBJ", 28),
   OBJ_AND_TWO_OBJ("OBJ_AND_TWO_OBJ", 29),
   TWO_OBJ_AND_OBJ("TWO_OBJ_AND_OBJ", 30),
   CUST("CUST", 31),
   SECTION_HEADER("SECTION_HEADER", 32),
   TWO_TX_TWO_OBJ("TWO_TX_TWO_OBJ", 33),
   OBJ_TX("OBJ_TX", 34),
   PIC_TX("PIC_TX", 35);
   // $FF: synthetic field
   private static final SlideLayout[] $VALUES = new SlideLayout[]{TITLE, TEXT, TWO_COL_TX, TBL, TEXT_AND_CHART, CHART_AND_TEXT, DGM, CHART, TX_AND_CLIP_ART, CLIP_ART_AND_TEXT, TITLE_ONLY, BLANK, TX_AND_OBJ, OBJ_AND_TX, OBJ_ONLY, TITLE_AND_CONTENT, TX_AND_MEDIA, MEDIA_AND_TX, OBJ_OVER_TX, TX_OVER_OBJ, TX_AND_TWO_OBJ, TWO_OBJ_AND_TX, TWO_OBJ_OVER_TX, FOUR_OBJ, VERT_TX, CLIP_ART_AND_VERT_TX, VERT_TITLE_AND_TX, VERT_TITLE_AND_TX_OVER_CHART, TWO_OBJ, OBJ_AND_TWO_OBJ, TWO_OBJ_AND_OBJ, CUST, SECTION_HEADER, TWO_TX_TWO_OBJ, OBJ_TX, PIC_TX};


   private SlideLayout(String var1, int var2) {}

}
