package org.apache.poi.xssf.usermodel;


public enum ListAutoNumber {

   ALPHA_LC_PARENT_BOTH("ALPHA_LC_PARENT_BOTH", 0),
   ALPHA_UC_PARENT_BOTH("ALPHA_UC_PARENT_BOTH", 1),
   ALPHA_LC_PARENT_R("ALPHA_LC_PARENT_R", 2),
   ALPHA_UC_PARENT_R("ALPHA_UC_PARENT_R", 3),
   ALPHA_LC_PERIOD("ALPHA_LC_PERIOD", 4),
   ALPHA_UC_PERIOD("ALPHA_UC_PERIOD", 5),
   ARABIC_PARENT_BOTH("ARABIC_PARENT_BOTH", 6),
   ARABIC_PARENT_R("ARABIC_PARENT_R", 7),
   ARABIC_PERIOD("ARABIC_PERIOD", 8),
   ARABIC_PLAIN("ARABIC_PLAIN", 9),
   ROMAN_LC_PARENT_BOTH("ROMAN_LC_PARENT_BOTH", 10),
   ROMAN_UC_PARENT_BOTH("ROMAN_UC_PARENT_BOTH", 11),
   ROMAN_LC_PARENT_R("ROMAN_LC_PARENT_R", 12),
   ROMAN_UC_PARENT_R("ROMAN_UC_PARENT_R", 13),
   ROMAN_LC_PERIOD("ROMAN_LC_PERIOD", 14),
   ROMAN_UC_PERIOD("ROMAN_UC_PERIOD", 15),
   CIRCLE_NUM_DB_PLAIN("CIRCLE_NUM_DB_PLAIN", 16),
   CIRCLE_NUM_WD_BLACK_PLAIN("CIRCLE_NUM_WD_BLACK_PLAIN", 17),
   CIRCLE_NUM_WD_WHITE_PLAIN("CIRCLE_NUM_WD_WHITE_PLAIN", 18);
   // $FF: synthetic field
   private static final ListAutoNumber[] $VALUES = new ListAutoNumber[]{ALPHA_LC_PARENT_BOTH, ALPHA_UC_PARENT_BOTH, ALPHA_LC_PARENT_R, ALPHA_UC_PARENT_R, ALPHA_LC_PERIOD, ALPHA_UC_PERIOD, ARABIC_PARENT_BOTH, ARABIC_PARENT_R, ARABIC_PERIOD, ARABIC_PLAIN, ROMAN_LC_PARENT_BOTH, ROMAN_UC_PARENT_BOTH, ROMAN_LC_PARENT_R, ROMAN_UC_PARENT_R, ROMAN_LC_PERIOD, ROMAN_UC_PERIOD, CIRCLE_NUM_DB_PLAIN, CIRCLE_NUM_WD_BLACK_PLAIN, CIRCLE_NUM_WD_WHITE_PLAIN};


   private ListAutoNumber(String var1, int var2) {}

}
