package org.apache.poi.ss.usermodel;


public enum IgnoredErrorType {

   CALCULATED_COLUMN("CALCULATED_COLUMN", 0),
   EMPTY_CELL_REFERENCE("EMPTY_CELL_REFERENCE", 1),
   EVALUATION_ERROR("EVALUATION_ERROR", 2),
   FORMULA("FORMULA", 3),
   FORMULA_RANGE("FORMULA_RANGE", 4),
   LIST_DATA_VALIDATION("LIST_DATA_VALIDATION", 5),
   NUMBER_STORED_AS_TEXT("NUMBER_STORED_AS_TEXT", 6),
   TWO_DIGIT_TEXT_YEAR("TWO_DIGIT_TEXT_YEAR", 7),
   UNLOCKED_FORMULA("UNLOCKED_FORMULA", 8);
   // $FF: synthetic field
   private static final IgnoredErrorType[] $VALUES = new IgnoredErrorType[]{CALCULATED_COLUMN, EMPTY_CELL_REFERENCE, EVALUATION_ERROR, FORMULA, FORMULA_RANGE, LIST_DATA_VALIDATION, NUMBER_STORED_AS_TEXT, TWO_DIGIT_TEXT_YEAR, UNLOCKED_FORMULA};


   private IgnoredErrorType(String var1, int var2) {}

}
