package org.apache.poi.ss.usermodel;


public enum PaperSize {

   LETTER_PAPER("LETTER_PAPER", 0),
   LETTER_SMALL_PAPER("LETTER_SMALL_PAPER", 1),
   TABLOID_PAPER("TABLOID_PAPER", 2),
   LEDGER_PAPER("LEDGER_PAPER", 3),
   LEGAL_PAPER("LEGAL_PAPER", 4),
   STATEMENT_PAPER("STATEMENT_PAPER", 5),
   EXECUTIVE_PAPER("EXECUTIVE_PAPER", 6),
   A3_PAPER("A3_PAPER", 7),
   A4_PAPER("A4_PAPER", 8),
   A4_SMALL_PAPER("A4_SMALL_PAPER", 9),
   A5_PAPER("A5_PAPER", 10),
   B4_PAPER("B4_PAPER", 11),
   B5_PAPER("B5_PAPER", 12),
   FOLIO_PAPER("FOLIO_PAPER", 13),
   QUARTO_PAPER("QUARTO_PAPER", 14),
   STANDARD_PAPER_10_14("STANDARD_PAPER_10_14", 15),
   STANDARD_PAPER_11_17("STANDARD_PAPER_11_17", 16);
   // $FF: synthetic field
   private static final PaperSize[] $VALUES = new PaperSize[]{LETTER_PAPER, LETTER_SMALL_PAPER, TABLOID_PAPER, LEDGER_PAPER, LEGAL_PAPER, STATEMENT_PAPER, EXECUTIVE_PAPER, A3_PAPER, A4_PAPER, A4_SMALL_PAPER, A5_PAPER, B4_PAPER, B5_PAPER, FOLIO_PAPER, QUARTO_PAPER, STANDARD_PAPER_10_14, STANDARD_PAPER_11_17};


   private PaperSize(String var1, int var2) {}

}
